"""refine processing_tasks relation to kb and doc

Revision ID: b1fc0a4988eb
Revises: 5a6ea187b7bd
Create Date: 2025-12-05 07:50:32.403396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1fc0a4988eb"
down_revision: Union[str, Sequence[str], None] = "5a6ea187b7bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Upgrade
    op.drop_constraint(
        op.f("processing_tasks_document_upload_id_fkey"),
        "processing_tasks",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("processing_tasks_knowledge_base_id_fkey"),
        "processing_tasks",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("processing_tasks_document_id_fkey"),
        "processing_tasks",
        type_="foreignkey",
    )

    op.create_foreign_key(
        "fk_processing_tasks_document_upload_id",
        "processing_tasks",
        "document_uploads",
        ["document_upload_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_processing_tasks_document_id",
        "processing_tasks",
        "documents",
        ["document_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_processing_tasks_knowledge_base_id",
        "processing_tasks",
        "knowledge_bases",
        ["knowledge_base_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_processing_tasks_document_upload_id",
        "processing_tasks",
        type_="foreignkey",
    )

    op.drop_constraint(
        "fk_processing_tasks_document_id",
        "processing_tasks",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_processing_tasks_knowledge_base_id",
        "processing_tasks",
        type_="foreignkey",
    )

    op.create_foreign_key(
        op.f("processing_tasks_document_id_fkey"),
        "processing_tasks",
        "documents",
        ["document_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("processing_tasks_knowledge_base_id_fkey"),
        "processing_tasks",
        "knowledge_bases",
        ["knowledge_base_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("processing_tasks_document_upload_id_fkey"),
        "processing_tasks",
        "document_uploads",
        ["document_upload_id"],
        ["id"],
    )
    # ### end Alembic commands ###
