"""add celery_task_id and job_type column to processing_tasks table

Revision ID: 5a6ea187b7bd
Revises: aa996fc7a0ae
Create Date: 2025-12-05 07:03:29.400891

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a6ea187b7bd"
down_revision: Union[str, Sequence[str], None] = "aa996fc7a0ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "processing_tasks",
        sa.Column("celery_task_id", sa.String(length=250), nullable=True),
    )
    op.add_column(
        "processing_tasks",
        sa.Column("job_type", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("processing_tasks", "job_type")
    op.drop_column("processing_tasks", "celery_task_id")
    # ### end Alembic commands ###
