name: Test Service

on:
  pull_request:
    branches: ['**']
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENV_FILE: .env.test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy test env file
        run: cp $ENV_FILE .env

      - name: Start isolated test services
        run: docker compose -f docker-compose.test.yml up -d --build

      - name: Run API tests
        run: docker compose exec -T main bash /test.sh api

      - name: Run e2e tests
        run: docker compose exec -T main bash /test.sh e2e

      - name: Run MCP tests
        run: docker compose exec -T main bash /test.sh mcp

      - name: Show logs if failure
        if: failure()
        run: docker compose logs

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.test.yml down -v
